// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Implements a Genkit flow that provides AI-driven suggestions on how to refine a user's prompt for better image generation results.
 *
 * - improvePromptQuality - A function that takes an initial prompt and returns suggestions for improvement.
 * - ImprovePromptQualityInput - The input type for the improvePromptQuality function.
 * - ImprovePromptQualityOutput - The return type for the improvePromptQuality function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImprovePromptQualityInputSchema = z.object({
  prompt: z.string().describe('The initial prompt provided by the user.'),
});
export type ImprovePromptQualityInput = z.infer<typeof ImprovePromptQualityInputSchema>;

const ImprovePromptQualityOutputSchema = z.object({
  suggestions: z
    .array(z.string())
    .describe('An array of AI-driven suggestions on how to refine the prompt.'),
});
export type ImprovePromptQualityOutput = z.infer<typeof ImprovePromptQualityOutputSchema>;

export async function improvePromptQuality(input: ImprovePromptQualityInput): Promise<ImprovePromptQualityOutput> {
  return improvePromptQualityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improvePromptQualityPrompt',
  input: {schema: ImprovePromptQualityInputSchema},
  output: {schema: ImprovePromptQualityOutputSchema},
  prompt: `You are an AI prompt engineer. Your goal is to help users refine their image generation prompts to achieve better results.

The user has provided the following initial prompt: "{{prompt}}".

Provide a list of suggestions on how to improve this prompt. These suggestions should be specific and actionable. Focus on suggesting concrete changes to the prompt that would lead to a better image, such as suggesting specific keywords, styles, or details to add.  Return your suggestions as a numbered list.
`,
});

const improvePromptQualityFlow = ai.defineFlow(
  {
    name: 'improvePromptQualityFlow',
    inputSchema: ImprovePromptQualityInputSchema,
    outputSchema: ImprovePromptQualityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
